spring:
  cloud:
    config:
      import-check:
        enabled: false
  datasource:
    url: 'jdbc:postgresql://localhost:5432/student'
    username: postgres
    password: password
    
  # For script based initialization, this should be set to true
  sql:
    init:
      mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true

    #    Scripts get executed before Hibernate is initialized
    defer-datasource-initialization: true
  hibernate:
    ddl-auto: create

server:
  port: 9292
  error:
    inlcude-message: always
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

  config:
    import: classpath:rabbitmq-config.yml
    
app:   
  app-name: DEV Config-DEV Config-DEV Config
  list: Dev,Config
  dbValues:
    connectionString: ${app.url}
    port: '3306'
  rabbitmq:
    - url: 'http://localhost:15672'
    - username: sm
    - password: sm
other:
  value: ${app.app-name}



