spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  cloud:
    config:
      import-check:
        enabled: false
  datasource:
    url: 'jdbc:postgresql://localhost:5432/student'
    username: postgres
    password: password
    
  # For script based initialization, this should be set to true
  sql:
    init:
      mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true

    #    Scripts get executed before Hibernate is initialized
    defer-datasource-initialization: true
  hibernate:
    ddl-auto: create

server:
  port: 9292
  error:
    inlcude-message: always
    
management:
  endpoints:
    web:
      exposure:
        include: health,refresh,beans,info

app:        
  my:
    greeting: CONFIG SERVER APP
    list:
      values: One, Two, Three, Four, Five
  message: 'HELLO CLIENT'
  rabbitmq:
    - host: localhost
    - port: 5672
    - username: sm
    - password: sm
  dbValues:
    connection: connection-string-here
    host: 127.0.0.1
    port: 1200




